filetype on
filetype plugin indent on
syntax enable

set autowriteall
set backspace=indent,eol,start
set breakindent
set completeopt=menuone,preview
set foldlevel=99
set foldmethod=indent
set lazyredraw
set mouse-=a
set number
set path+=**
set relativenumber
set shortmess+=A
set signcolumn=no
set smartcase
set splitbelow
set splitright
set termguicolors
set virtualedit=insert
set wildcharm=<TAB>
set wildignore+=*.pyc,*.so,*.swp,*.zip,.*/**
set wildmenu
set winminheight=0

if !has('nvim')
    set encoding=utf-8
    set hlsearch
    set incsearch
endif

set grepprg=grep\ -rIHnP\ --exclude-dir='.*'

if has("persistent_undo")
    set undodir=~/.undodir/
    set undofile
endif

if has('nvim')
    set inccommand=nosplit
endif

silent! colorscheme solarized
set bg=dark

let mapleader = "\<Space>"
nnoremap <silent> <leader>* :let @/ = '\<' . expand('<cword>') . '\>' <bar> set hlsearch<CR>
nnoremap <TAB> <C-w>w
nnoremap <S-TAB> <C-w>p
nnoremap <C-L> 20zl
nnoremap <C-H> 20zh

cmap w!! w !sudo tee % >/dev/null

augroup myvimrc
    au!
    au BufWritePost .vimrc source $MYVIMRC
    au BufWritePost vimrc source $MYVIMRC
    au BufEnter .vimrc set ft=vim
augroup END

let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_delay = 50

augroup SmartNumbers
    au!
    au BufEnter,WinEnter * if &buftype == '' | set number | set relativenumber | endif
    au BufLeave,WinLeave * set norelativenumber
    au FocusLost * set norelativenumber
    au FocusGained * if &buftype == '' | set relativenumber | endif
augroup END

set ts=4 sts=4 sw=4 expandtab
augroup indent
    au!
    au FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
    au FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
    au FileType html setlocal ts=2 sts=2 sw=2 expandtab
    au FileType json setlocal ts=2 sts=2 sw=2 expandtab
    au FileType javascript setlocal ts=2 sts=2 sw=2 expandtab
    au FileType css setlocal ts=2 sts=2 sw=2 expandtab
augroup END

fun! MaximizeOrEqualize()
    if &columns < 170
        wincmd |
        wincmd _
    else
        wincmd =
    endif
endf

fun! MaximizeOrNothing()
    if &columns < 170
        wincmd |
        wincmd _
    endif
endf

augroup Resize
    autocmd!
    au VimResized * call MaximizeOrEqualize()
    au WinEnter * call MaximizeOrNothing()
augroup END

augroup ColorColumn
    au!
    autocmd WinEnter,BufEnter *.py\|*.vim\|*vimrc call matchadd('ColorColumn', '\%81v', 100)
augroup END

let g:python3_host_prog = $HOME.'/.venv/bin/python'

augroup AutoWrite
    au!
    au BufWritePre * call system('mkdir -p '.shellescape(expand('%:p:h')))
    au CursorHold * checktime
    au FocusLost * silent! wall
    au FocusGained * if &buftype == '' | checktime | endif
augroup END

set statusline=%f\ %m\ %h\ %r\ %{winnr()}\%=%l:%v/%L\ %p%%
augroup StatusLine
    au!
    au WinEnter,WinLeave,WinNew * redrawstatus!
augroup END

inoremap <silent> <expr> <TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <silent> <expr> <S-TAB> pumvisible() ? "\<C-p>" : "\<S-TAB>"

cnoremap <expr> <Tab> index(['/', '?'], getcmdtype()) == -1 ? "<TAB>": "<C-G>" 
cnoremap <expr> <S-Tab> index(['/', '?'], getcmdtype()) == -1 ? "<S-TAB>": "<C-T>" 

nnoremap <F12> <C-i>

augroup RestoreCursor
    au!
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
augroup END
