#! /usr/bin/env zsh

setopt pipefail
comm=$1
shift
case $comm in
    pytest)
        force_color="--color=yes"
        ;;
    *)
        force_color=""
esac
if [[ $(uname) == 'Darwin' ]]; then
    alias md5='md5 -r'
else
    alias md5=md5sum
fi
local previous_out_hash=''
test -e /tmp/out && previous_out_hash=$(md5 /tmp/out | awk '{print $1}')
sleep 0.01
$comm $force_color $@ | tee /tmp/out
if [[ $? -eq 0 ]]; then
    if [[ $previous_out_hash == $(md5 /tmp/out | awk '{print $1}') ]]; then
        if [[ $(uname) == 'Darwin' ]]; then
            osascript -e 'display notification "all tests passed"'
        else
            notify-send 'all tests passed'
        fi
    else
        sleep 1
    fi
    tmux select-pane -t.0 \; resize-pane -Z
else
    line_count=$(wc -l /tmp/out | awk '{print $1}')
    if [[ $line_count -gt $LINES ]]; then
        grep -q -e '(Pdb\(++\)\?)' /tmp/out
        if [[ $? -eq 1 ]]; then
            less +G /tmp/out
            tmux select-pane -t.0 \; resize-pane -Z
        fi
    fi
fi
unsetopt pipefail
