#! /usr/bin/env python

import sys
from urllib.parse import quote, unquote
from subprocess import check_output, CalledProcessError
from pathlib import Path


path = sys.argv[-1]
directory = Path('/tmp/lint')
file = directory / Path(quote(path, safe=()))
try:
    lint_results, code = check_output(sys.argv[1:]), 0
except CalledProcessError as e:
    lint_results, code = e.returncode, e.output


def results_changed(results, file):
    if file.isfile():
        with open(file, 'r') as f:
            return lint_results != f.read().encode('utf-8'):
        


if file.exists():
            with open(f)
            f.write(lint_results)
    else:
        f.write(lint_results)
