#! /usr/bin/env python3

import sys
from urllib.parse import quote
from subprocess import PIPE, Popen
from pathlib import Path


def results_changed(results, file):
    try:
        with open(file, 'r') as f:
            return results != f.read()
    except FileNotFoundError:
        return True


args = sys.argv[1:]
use_stdin = args[-1] == '--stdin'
if use_stdin:
    args.pop()
    filename = args.pop()
else:
    filename = args[-1]
directory = Path('/tmp/lint')
directory.mkdir(exist_ok=True)
file = directory / Path(quote(filename, safe=()))
p = Popen(args, stdin=sys.stdin, stderr=PIPE, stdout=PIPE)
lint_results = str(p.communicate()[0], 'utf-8')
print(lint_results)
if results_changed(lint_results, file):
    with open(file, 'w') as f:
        f.write(lint_results)
