#! /usr/bin/env bash

git ls-files -co --exclude-standard \
    | awk -F\. '{print $NF}' | sort -u \
    | parallel "test -e ~/vimconf/git_hooks/{}/$1 && readlink -f ~/vimconf/git_hooks/{}/$1" \
    | uniq | parallel find {} -type f | parallel
