#! /usr/bin/env bash

inotifywait -r -m -e close_write -q $1 |
while read -r directory events filename; do
    clear
    if ! tmux list-panes -F '#{window_visible_layout}' | grep -q '\{'; then
        tmux resize-pane -Z
    else
        tmux select-pane -t:.$TMUX_PANE -P 'bg=yellow,fg=black'
        sleep 0.3; tmux select-pane -t:.$TMUX_PANE -P 'bg=default,fg=default' &
    fi
    cat $directory/$filename
done
