#! /usr/bin/env zsh
[[ -d "$1" ]] && directory=$1 || directory='.'
cd $directory
for rem in $(git remote); do
	oldurl=$(git remote get-url --push $rem)
    git remote set-url --push $rem $(git remote get-url --push $rem | perl -pe 's/https:\/\/([^\/]+)\/(.*)/git@\1:\2/g')
done

